version: '3'

services:
  server:
    container_name: infosistemas-vehicle-server
    image: latest/infosistemas-vehicle-server
    restart: always
    build: .
    ports:
      - "4000:4000"
      - "56745:56745"
    links:
      - mongo
    command: npm run dev
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27018'
    command: mongod --port 27018 --bind_ip_all
