openapi: 3.0.0

servers:
  # Added by API Auto Mocking Plugin
  - description: Development
    url: https://localhost:4000/

info:
  description: "Essa API é um toy program para um CRUD de veiculos"
  version: 1.0.0
  title: Infosistemas Vehicle API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
  - name: Todos
    description: Operations available to all users

paths:
  /vehicle:
    get:
      tags:
        - Todos
      summary: Lista os veiculos da plataforma
      operationId: listVehicles
      description: Lista todos os veiculos para um recurso
      parameters:
        - in: header
          name: Content-Type
          schema:
            type: string
            default: 'application/json'
        - in: query
          name: max
          schema:
            type: number
            default: 10
            description: Quantidade máxima de veiculos a ser listada
        - in: query
          name: offset
          schema:
            type: number
            default: 0
            description: Quantidade de veiculos para pular na lista
      responses:
        200:
          description: Lista de veiculos para esse resource
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
        500:
          description: Erro interno, chame o suporte.
    post:
      tags:
        - Todos
      parameters:
        - in: header
          name: Content-Type
          schema:
            type: string
            default: 'application/json'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateVehicle'
      responses:
        201:
          description: veiculo criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        500:
          description: Validation error

  /vehicle/{id}:
    delete:
      tags:
        - Todos
      parameters:
        - in: header
          name: Content-Type
          schema:
            type: string
            default: 'application/json'
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        201:
          description: Veiculo deleteado
        404:
          description: id invalido, veiculo não encontrado
    get:
      tags:
        - Todos
      parameters:
        - in: header
          name: Content-Type
          schema:
            type: string
            default: 'application/json'
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
      responses:
        201:
          description: Veiculo encontrado
        404:
          description: id invalido, veiculo não encontrado
    put:
      tags:
        - Todos
      parameters:
        - in: header
          name: Content-Type
          schema:
            type: string
            default: 'application/json'
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateVehicle'
      responses:
        201:
          description: veiculo atualizado
        500:
          description: invalid input, object invalid
components:
  schemas:
    Vehicle:
      type: object
      required:
        - body
        - resource
      properties:
        _id:
          type: string
        placa:
          type: string
        chassi:
          type: string
        renavam:
          type: string
        modelo:
          type: string
        marca:
          type: string
        ano:
          type: number
    CreateVehicle:
      type: object
      required:
        - placa
        - chassi
        - renavam
        - modelo
        - marca
        - ano
      properties:
        placa:
          type: string
        chassi:
          type: string
        renavam:
          type: string
        modelo:
          type: string
        marca:
          type: string
        ano:
          type: number
    UpdateVehicle:
      type: object
      properties:
        placa:
          type: string
        chassi:
          type: string
        renavam:
          type: string
        modelo:
          type: string
        marca:
          type: string
        ano:
          type: number

